#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

readonly OPTIONS_FILE=/data/options.json
readonly GENERATED_CONF=/data/srs.conf
readonly USER_CONF=/addon_config/srs.conf
readonly SRS_HOME=/usr/local/srs

log() { printf '[srs] %s\n' "$*" >&2; }

opt() {
    jq -r --arg key "$1" '.[$key] // empty' "$OPTIONS_FILE"
}

flag() {
    jq -r --arg key "$1" 'if .[$key] == true then "true" else "false" end' "$OPTIONS_FILE"
}

if [[ ! -f "$OPTIONS_FILE" ]]; then
    log "ERROR: missing options file: $OPTIONS_FILE"
    exit 1
fi

TZ_VALUE="$(opt timezone)"
LOG_LEVEL="$(opt log_level)"
CANDIDATE="$(opt webrtc_candidate)"
WEBRTC_TCP="$(flag webrtc_tcp_enabled)"
SRT_ENABLED="$(flag srt_enabled)"

[[ -n "$LOG_LEVEL" ]] || LOG_LEVEL=info
[[ -n "$CANDIDATE" ]] || CANDIDATE='*'

if [[ -n "$TZ_VALUE" ]]; then
    export TZ="$TZ_VALUE"
    log "Timezone: $TZ_VALUE"
fi

WEBRTC_PROTOCOL=udp
RTC_TCP_BLOCK=""
if [[ "$WEBRTC_TCP" == "true" ]]; then
    WEBRTC_PROTOCOL=all
    RTC_TCP_BLOCK="    tcp {
        enabled on;
        listen 8000;
    }"
fi

SRT_BLOCK=""
if [[ "$SRT_ENABLED" == "true" ]]; then
    SRT_BLOCK="srt_server {
    enabled on;
    listen 10080;
}"
fi

generate_conf() {
    cat > "$GENERATED_CONF" <<EOF
# Generated by the SRS Home Assistant app from the app options.
# For full control, place your own srs.conf at /addon_config/srs.conf;
# it replaces this file completely.
listen              1935;
max_connections     1000;
srs_log_tank        console;
srs_log_level       $LOG_LEVEL;
daemon              off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled on;
    listen 8000;
    candidate $CANDIDATE;
    protocol $WEBRTC_PROTOCOL;
$RTC_TCP_BLOCK
}
$SRT_BLOCK
vhost __defaultVhost__ {
    hls {
        enabled on;
    }
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled on;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
    }
}
EOF
}

if [[ -s "$USER_CONF" ]]; then
    CONF_FILE="$USER_CONF"
    log "Using custom SRS config: $USER_CONF"
else
    generate_conf
    CONF_FILE="$GENERATED_CONF"
    log "Generated config: $GENERATED_CONF (log level: $LOG_LEVEL, WebRTC candidate: $CANDIDATE, SRT: $SRT_ENABLED)"
fi

cd "$SRS_HOME"
log "Starting SRS: RTMP :1935, HTTP API :1985, HTTP :8080, WebRTC UDP :8000"

exec ./objs/srs -c "$CONF_FILE"
